// demos/electron/react/src/pages/Home.tsx
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { isAuthenticated } from "../../../../shared/utils/auth";
import "./Home.css";

export default function Home() {
  const navigate = useNavigate();

  useEffect(() => {
    // 检查登录状态
    if (!isAuthenticated()) {
      navigate("/");
    }
  }, [navigate]);

  return (
    <div className="home-container">
      <div className="home-content">
        <h1>Hello World</h1>
        <p className="home-subtitle">Welcome to RTM SDK Demo</p>
      </div>
    </div>
  );
}

// demos/electron/vue/src/pages/Home.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useRouter } from "vue-router";
import { isAuthenticated } from "../../../../shared/utils/auth";

const router = useRouter();

onMounted(() => {
  // 检查登录状态
  if (!isAuthenticated()) {
    router.push("/");
  }
});
</script>

<template>
  <div class="home-container">
    <div class="home-content">
      <h1>Hello World</h1>
      <p class="home-subtitle">Welcome to RTM SDK Demo</p>
    </div>
  </div>
</template>

<style scoped src="./Home.css"></style>
