// demos/electron/vue/src/components/TeacherList.vue
<script setup lang="ts">
import type { User } from "../stores/rtm";
import { useChatStore } from "../stores/chat";

interface Props {
  teachers: User[];
}

defineProps<Props>();
const emit = defineEmits<{
  teacherClick: [teacher: User];
}>();

const chatStore = useChatStore();
</script>

<template>
  <div class="teacher-list-container">
    <h2 class="teacher-list-title">Teacher List</h2>
    <div class="teacher-list">
      <div
        v-for="teacher in teachers"
        :key="teacher.userId"
        class="teacher-list-item"
        @click="emit('teacherClick', teacher)"
      >
        <span class="teacher-list-avatar">{{ teacher.avatar }}</span>
        <span class="teacher-list-name">{{ teacher.name }}</span>
        <span
          v-if="chatStore.unreadCounts[teacher.userId]"
          class="teacher-list-badge"
        >
          {{ chatStore.unreadCounts[teacher.userId] }}
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped src="./styles/TeacherList.css"></style>

// demos/react/webpack/src/components/TeacherList.tsx
import { type User } from "../store/rtm";
import { useChatStore } from "../store/chat";
import "./styles/TeacherList.css";

interface TeacherListProps {
  teachers: User[];
  onTeacherClick: (teacher: User) => void;
}

export default function TeacherList({
  teachers,
  onTeacherClick,
}: TeacherListProps) {
  const unreadCounts = useChatStore((state) => state.unreadCounts);

  return (
    <div className="list-container">
      <h2 className="list-title">Teacher List</h2>
      <div className="list-items">
        {teachers.map((teacher) => {
          const unread = unreadCounts[teacher.userId] || 0;
          return (
            <div
              key={teacher.userId}
              className="list-item"
              onClick={() => onTeacherClick(teacher)}
            >
              <span className="list-avatar">{teacher.avatar}</span>
              <span className="list-name">{teacher.name}</span>
              {unread > 0 && <span className="list-badge">{unread}</span>}
            </div>
          );
        })}
      </div>
    </div>
  );
}
