// demos/electron/vue/src/components/StudentList.vue
<script setup lang="ts">
import type { User } from "../types/user";
import { useChatStore } from "../stores/chat";

interface Props {
  students: User[];
}

defineProps<Props>();
const emit = defineEmits<{
  studentClick: [student: User];
}>();

const chatStore = useChatStore();
</script>

<template>
  <div class="student-list-container">
    <h2 class="student-list-title">Student List</h2>
    <div class="student-list">
      <div
        v-for="student in students"
        :key="student.userId"
        class="student-list-item"
        @click="emit('studentClick', student)"
      >
        <span class="student-list-avatar">{{ student.avatar }}</span>
        <span class="student-list-name">{{ student.name }}</span>
        <span
          v-if="chatStore.unreadCounts[student.userId]"
          class="student-list-badge"
        >
          {{ chatStore.unreadCounts[student.userId] }}
        </span>
      </div>
    </div>
  </div>
</template>

<style scoped src="./StudentList.css"></style>

// demos/electron/react/src/components/StudentList.tsx
import type { User as Student } from "../types/user";
import { useChatStore } from "../store/chat";
import "./StudentList.css";

interface StudentListProps {
  students: Student[];
  onStudentClick: (student: Student) => void;
}

export default function StudentList({
  students,
  onStudentClick,
}: StudentListProps) {
  const unreadCounts = useChatStore((state) => state.unreadCounts);

  return (
    <div className="student-list-container">
      <h2 className="student-list-title">Student List</h2>
      <div className="student-list">
        {students.map((student) => {
          const unread = unreadCounts[student.userId] || 0;
          return (
            <div
              key={student.userId}
              className="student-list-item"
              onClick={() => onStudentClick(student)}
            >
              <span className="student-list-avatar">{student.avatar}</span>
              <span className="student-list-name">{student.name}</span>
              {unread > 0 && (
                <span className="student-list-badge">{unread}</span>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
