// demos/electron/vue/src/components/ClassroomList.vue
<script setup lang="ts">
import type { Classroom } from "../types/chat";

interface Props {
  classrooms: Classroom[];
}

defineProps<Props>();
const emit = defineEmits<{
  classroomClick: [classroom: Classroom];
}>();
</script>

<template>
  <div class="classroom-list-container">
    <h2 class="classroom-list-title">Classroom Channels</h2>
    <div class="classroom-list">
      <div
        v-for="classroom in classrooms"
        :key="classroom.id"
        class="classroom-list-item"
        @click="emit('classroomClick', classroom)"
      >
        <span class="classroom-list-icon">📚</span>
        <span class="classroom-list-name">{{ classroom.name }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped src="./ClassroomList.css"></style>

// demos/h5/src/components/ClassroomList.tsx
import type { Classroom } from "../types/chat";
import "./ClassroomList.less";

interface ClassroomListProps {
  classrooms: Classroom[];
  onClassroomClick: (classroom: Classroom) => void;
}

export default function ClassroomList({
  classrooms,
  onClassroomClick,
}: ClassroomListProps) {
  return (
    <div className="classroom-list-container">
      <h2 className="classroom-list-title">Classroom Channels</h2>
      <div className="classroom-list">
        {classrooms.map((classroom) => (
          <div
            key={classroom.id}
            className="classroom-item"
            onClick={() => onClassroomClick(classroom)}
          >
            <span className="classroom-icon">📚</span>
            <span className="classroom-name">{classroom.name}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
